debug: true
preload: true

dialog-box:
  delay: 60
  #alpha: 0.3
  endPoint: true

publish:
  host: http://vnjson.mcap.fun
  token: 3ba79c3ecaf5c171072a3a19f41539a0

menu:
  audio: sysFlipPages
  volume: 0.1
  
main-menu:
  audio: test22
  volume: 0.1
  
discord-log:
  webhook: https://discord.com/api/webhooks/995314212500938789/C4ul6cKMwYadYYaOCSyla_dlwDVd1IPSZu0wb24l9kkjo971QCfdHolkEPrExR2KcpzO
# console-port: 8082
# chess: false
# paint-board: false
# crossword: false