#################################
debug: true
#################################
preload: true

publish:
  host: http://vnjson.mcap.fun
  token: b38ed838f352f6ad7f842bf497800feb

discord-log:
  webhook: https://discord.com/api/webhooks/995314212500938789/C4ul6cKMwYadYYaOCSyla_dlwDVd1IPSZu0wb24l9kkjo971QCfdHolkEPrExR2KcpzO
# console-port: 8082
# iframe modules
# chess: false
# paint-board: false
# crossword: false
# ide: false